[package]
name = "website_status_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "2.12.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
ctrlc = "3.2.3"

[dev-dependencies]
assert_cmd = "2.0.0"   